[package]
name = "runner"
version = "0.1.0"
edition = "2021"
build="build.rs"

[dependencies]
aoc = { path = "../aoc" }
day1 = { path = "../day1" }
day2 = { path = "../day2" }
day3 = { path = "../day3" }
day4 = { path = "../day4" }
day5 = { path = "../day5" }
tokio = { version="1.41.1", features = ["full"] }
url = "2.5.4"