[package]
name = "runner"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
getopts = "*"
aoc = { path = "../aoc" }
day1 = { path = "../day1" }
day2 = { path = "../day2" }
day3 = { path = "../day3" }
day4 = { path = "../day4" }
day5 = { path = "../day5" }
day6 = { path = "../day6" }
day7 = { path = "../day7" }
day9 = { path = "../day9" }
day10 = { path = "../day10" }
day11 = { path = "../day11" }
day13 = { path = "../day13" }
tokio = { version = "1.41.1", features = ["full"] }
url = "2.5.4"
